import { Article, getArticles } from '@/lib/learn';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head'
import Link from 'next/link';

export default function GrammerHome({ articles }: InferGetStaticPropsType<typeof getStaticProps>) {

  // const posts: any = props.posts;

  return (
    <>
      <Head>
        <title>Platform for Learning Magar Language | Magar Dhut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='min-vh-100 '>
        <section className='col-md-12 bg-warning mb-3' style={{ height: ' 25vh !important' }}>
          <section className='text-center p-5'>
            <h1>Basic Grammer</h1>
            <p>Magar to Nepali and Nepali to Magar Dictionary</p>
          </section>

        </section>
        <div className='container'>
          <div className="list-group">
            {
              articles.map((a) => (
                <Link className='list-group-item list-group-item-action active' aria-current='true' key={a.id}
                  href={`/learn/grammer/${a.id}`}
                >
                  <div className="d-flex w-100 justify-content-between">
                    <h5 className="mb-1">{a.title}</h5>
                    <small>{a.date}</small>
                  </div>
                  <p className="mb-1">{a.description}</p>
                  {/* <small>And some small print.</small> */}
                </Link>
                // <a href="#" className="" aria-current="true" key={a.id}>

                // </a>
              )
              )}
          </div>
        </div>
      </div>

    </>
  )
}

export const getStaticProps: GetStaticProps<{ articles: Article[] }> = async (context) => {
  const articles = getArticles('grammer');
  return {
    props: {
      articles
    }
  };
}