import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Post, getSortedPostsData } from '@/lib/posts'
import Link from 'next/link'
import { GetStaticProps, InferGetStaticPropsType } from 'next'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {

  // const posts: any = props.posts;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <h5>Blog</h5>
        <ul>
          {
            posts.map(({ id, date, title }) =>
            (
              <li key={id}><Link href={`/posts/${id}`}>{title} </Link><br /> {id} <br /> {date}</li>
            )
            )
          }
        </ul>
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps<{posts: Post[]}> = async (context) => {
  const posts = getSortedPostsData();
  return {
    props: {
      posts
    }
  };
}