import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getSortedPostsData } from '@/lib/posts'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h5>Blog</h5>
        <ul>
          {
            posts.map(({ id, date, title }) =>
            (
              <li key={id}><Link href={`/posts/${id}`}>{title} </Link><br /> {id} <br /> {date}</li>
            )
            )
          }
        </ul>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const posts = getSortedPostsData();
  return {
    props: {
      posts,
    },
  };
}