import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Post, getSortedPostsData } from '@/lib/posts'
import Link from 'next/link'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import { Button, Card } from 'react-bootstrap'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {

  // const posts: any = props.posts;

  return (
    <>
      <Head>
        <title>Platform for Learning Magar Language | Magar Dhut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-vh-100 '>
        <section className='col-md-12 bg-warning mb-3' style={{ height: ' 25vh !important' }}>
          <section className='text-center p-5'>
            <h1>Magardhut</h1>
            <p>Platform for Learning Magar Language (Dhut)</p>
          </section>

        </section>
        <div className='container'>
          <div className="row mb-3">
            <div className="col-md-4">
              <Card>
                {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                <Card.Body>
                  <Card.Title className='text-center'>Vocabularies</Card.Title>
                  <Card.Text className='text-justify'>
                    Learn Magar Language Vocabolaries on different categories
                  </Card.Text>
                </Card.Body>
                <Card.Footer>
                  <Button variant="primary">Go somewhere</Button>
                </Card.Footer>
              </Card>
            </div>
            <div className="col-md-4">
              <Card>
                {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                <Card.Body>
                  <Card.Title className='text-center'>Basic Grammer</Card.Title>
                  <Card.Text className='text-justify'>
                    Learn Magar Language Grammer and Sentence Composition
                  </Card.Text>
                </Card.Body>
                <Card.Footer>
                  <Button variant="primary">Go somewhere</Button>
                </Card.Footer>
              </Card>

            </div>

            <div className="col-md-4">
              <Card>
                {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                <Card.Body>
                  <Card.Title className='text-center'>Conversation</Card.Title>
                  <Card.Text className='text-justify'>
                    Learn How to start conversation on different topics
                  </Card.Text>
                </Card.Body>
                <Card.Footer>
                  <Button variant="primary">Go somewhere</Button>
                </Card.Footer>
              </Card>

            </div>

          </div>

          <div className="row">
            <div className="col-md-4">
              <Card>
                {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                <Card.Body>
                  <Card.Title className='text-center'>Formation of Words</Card.Title>
                  <Card.Text className='text-justify'>
                    Learn How to form words in different scenarios
                  </Card.Text>
                </Card.Body>
                <Card.Footer>
                  <Button variant="primary">Go somewhere</Button>
                </Card.Footer>
              </Card>

            </div>
          </div>
        </div>
      </div>
      
    </>
  )
}

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async (context) => {
  const posts = getSortedPostsData();
  return {
    props: {
      posts
    }
  };
}