import Head from 'next/head'
import { Inter } from 'next/font/google'
import CategoryCard from '@/components/categoryCard/categoryCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Platform for Learning Magar Language | Magar Dhut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='min-vh-100 '>
        <section className='bg-warning mb-3' style={{ height: ' 25vh !important' }}>
          <section className='text-center p-5'>
            <h1>Dictionary</h1>
            <p>Magar to Nepali and Nepali to Magar Dictionary</p>
          </section>

        </section>
        <div className='container'>
          <div className="row mb-3">
            <div className="col-md-6">
              <CategoryCard
                image='/undraw_Personal_notebook.png'
                date='Last Updated 3 mins ago'
                title='Magar To Nepali Dictionary'
                route='/dictionary/magar-to-nepal'
                description='Browse Magar words to know the meaning in Nepali Language'
              />
            </div>

            <div className="col-md-6">
              <CategoryCard
                image='/undraw_Personal_notebook.png'
                date='Last Updated 3 mins ago'
                title='Nepali To Magar Dictionary'
                route='/dictionary/nepali-to-magar'
                description='Browse Nepali words to know them in Magar Language'
              />
            </div>

          </div>
        </div>
      </div>

    </>
  )
}